# Generated by Django 4.1.5 on 2023-01-29 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='main_crop',
            fields=[
                ('crop_id', models.AutoField(primary_key=True, serialize=False)),
                ('crop_name', models.CharField(max_length=150)),
                ('crop_date', models.DateField()),
                ('crop_notes', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='worker',
            fields=[
                ('worker_no', models.AutoField(primary_key=True, serialize=False)),
                ('worker_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('amount', models.IntegerField()),
                ('worker_notes', models.TextField(max_length=200)),
                ('crop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.main_crop')),
            ],
        ),
        migrations.CreateModel(
            name='medicine',
            fields=[
                ('med_id', models.AutoField(primary_key=True, serialize=False)),
                ('med_name', models.CharField(max_length=150)),
                ('date', models.DateField()),
                ('bill_no', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('amount', models.FloatField()),
                ('med_notes', models.TextField(max_length=200)),
                ('crop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.main_crop')),
            ],
        ),
        migrations.CreateModel(
            name='feed',
            fields=[
                ('feed_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('shop_name', models.CharField(max_length=150)),
                ('bill_no', models.CharField(max_length=100)),
                ('bill_amount', models.FloatField()),
                ('feed_notes', models.TextField(max_length=200)),
                ('crop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.main_crop')),
            ],
        ),
        migrations.CreateModel(
            name='export',
            fields=[
                ('exp_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('tank_no', models.CharField(max_length=100)),
                ('material_weight', models.FloatField()),
                ('count', models.FloatField()),
                ('amount', models.FloatField()),
                ('exp_notes', models.TextField(max_length=200)),
                ('crop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.main_crop')),
            ],
        ),
        migrations.CreateModel(
            name='expenses',
            fields=[
                ('exp_no', models.AutoField(primary_key=True, serialize=False)),
                ('exp_name', models.CharField(max_length=150)),
                ('exp_cost', models.CharField(max_length=150)),
                ('exp_date', models.DateField()),
                ('exp_paidto', models.CharField(max_length=100)),
                ('exp_notes', models.TextField(max_length=250)),
                ('crop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.main_crop')),
            ],
        ),
        migrations.CreateModel(
            name='ele_bill',
            fields=[
                ('bill_id', models.AutoField(primary_key=True, serialize=False)),
                ('tranformer_type', models.CharField(max_length=50)),
                ('billed_date', models.DateField()),
                ('start_read', models.IntegerField()),
                ('end_read', models.IntegerField()),
                ('bill_amount', models.FloatField()),
                ('bill_notes', models.TextField(max_length=200)),
                ('crop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.main_crop')),
            ],
        ),
    ]
