# Generated by Django 4.1.5 on 2023-01-29 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sample',
            fields=[
                ('crop_id', models.AutoField(primary_key=True, serialize=False)),
                ('crop_name', models.CharField(max_length=150)),
                ('crop_date', models.DateField()),
                ('crop_notes', models.TextField(max_length=200)),
            ],
        ),
    ]
