# Generated by Django 4.1.5 on 2023-01-29 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_sample'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='crop_id',
            field=models.IntegerField(),
        ),
    ]
