# Generated by Django 4.1.5 on 2023-01-29 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_expenses_crop_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sample',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='crop_id',
        ),
        migrations.AlterField(
            model_name='ele_bill',
            name='crop_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='export',
            name='crop_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='feed',
            name='crop_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='crop_id',
            field=models.IntegerField(),
        ),
    ]
