# Generated by Django 4.1.5 on 2023-01-29 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_delete_sample_remove_worker_crop_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='exp_cost',
            field=models.IntegerField(),
        ),
    ]
