# Generated by Django 4.1.5 on 2023-02-04 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_sample'),
    ]

    operations = [
        migrations.CreateModel(
            name='daily_feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('tank_no', models.CharField(max_length=50)),
                ('first', models.FloatField()),
                ('second', models.FloatField()),
                ('third', models.FloatField()),
                ('fourth', models.FloatField()),
                ('crop_id', models.IntegerField()),
            ],
        ),
    ]
