# Generated by Django 4.1.5 on 2023-02-05 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_worker_crop_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
