# Generated by Django 4.1.5 on 2023-02-16 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_feed_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='main_crop',
            name='location',
            field=models.CharField(default='sanavilli', max_length=100),
            preserve_default=False,
        ),
    ]
