# Generated by Django 4.1.5 on 2023-02-23 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_main_crop_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='main_crop',
            name='days',
            field=models.IntegerField(null=True),
        ),
    ]
